// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';
import {object} from '../models';

export function ChooseFolder():Promise<string>;

export function GetConfig(arg1:string):Promise<string>;

export function GetGitStatus(arg1:string):Promise<git.Status>;

export function GitAddAllFiles(arg1:string):Promise<void>;

export function GitCheckout(arg1:string,arg2:string):Promise<void>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitGetLastCommit(arg1:string):Promise<object.Commit>;

export function GitLog(arg1:string):Promise<Array<object.Commit>>;

export function InitGitRepoIfNotExists(arg1:string):Promise<void>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;
