// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder():Promise<string>;

export function GetGitStatus(arg1:string):Promise<string>;

export function InitGitRepoIfNotExists(arg1:string):Promise<void>;
