// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';

export function ChooseFolder():Promise<string>;

export function GetGitStatus(arg1:string):Promise<git.Status>;

export function InitGitRepoIfNotExists(arg1:string):Promise<void>;
